server:
  port: 9000

spring:
  datasource:
    password: asd124563
    username: root
    url: jdbc:mysql://localhost:3306/sunreaver-cloud-file?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

